name: CI/CD -> Minify, compress and deploy
on:
  push:
    branches: [master, dev]
concurrency: 
  group: deploy
  cancel-in-progress: true    
jobs:
  compress:
    name: 🖼️ Compress
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      # Minify Files
      - name: 🔨 Compress Web files
        uses: zugazagoitia/minify-js@v0.4
      # Compress Images
      - name: 🗜️ Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          compressOnly: true
      - name: Cache
        uses: actions/cache@v2
        with:
          path: .
          key: ${{ github.event.head_commit.id }} 
      
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    needs:
      - compress

    steps:
      # Deploy  
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: .
          key: ${{ github.event.head_commit.id }}  

      - name: 📂 SFTP Sync
        uses: swillner/sftp-sync-action@v1.0
        with:
          server: ${{ secrets.SSH_SERVER }}
          user: ${{ secrets.SSH_USERNAME }}
          user_private_key:  ${{ secrets.SSH_PRIVATE_KEY }}
          host_public_key:  ${{ secrets.SSH_SERVER_PUBLIC_KEY }}
          remote: ${{ secrets.SSH_REMOTE_DIR }}
          mirror_options: "--exclude-glob=.git*/"   

      - name: ☁️ Cloudflare Purge Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
