name: CD -> Build and deploy
on:
  push:
    branches: [master, dev]
concurrency: 
  group: deploy
  cancel-in-progress: true    
jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: 🔨 Build
        run: ./build-gallery.sh

      - name: 📂 SFTP Sync (PROD)
        uses: burnett01/rsync-deployments@5.2.1
        if: endsWith(github.ref, '/master')        
        with:
          switches: -vzr --delete
          path: src/
          remote_path: ${{ secrets.SSH_REMOTE_DIR }}
          remote_host: ${{ secrets.SSH_SERVER }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}  

      - name: 📂 SFTP Sync (DEV)
        uses: burnett01/rsync-deployments@5.2.1
        if: endsWith(github.ref, '/dev')        
        with:
          switches: -vzr --delete
          path: src/
          remote_path: ${{ secrets.SSH_REMOTE_DIR_STAGING }}
          remote_host: ${{ secrets.SSH_SERVER }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}            

      - name: ☁️ Cloudflare Purge Cache
        uses: jakejarvis/cloudflare-purge-action@v0.3.0
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
